### ISSUE TITLE
FYI: This is what the theme looks like when you install it on a fresh Neto trial from the theme store

### ISSUE THREAD

**Issue by brandonsheppard** [demiscient/demitheme#14]
<img width="1500" alt="premiumthemes 20160719" src="https://cloud.githubusercontent.com/assets/5397325/16943394/ee6db8b8-4dde-11e6-80ed-df3276c2aa9f.png">

<img width="1500" alt="our blog 20160719" src="https://cloud.githubusercontent.com/assets/5397325/16943447/21f5d738-4ddf-11e6-9d3c-3ba335a22b81.png">
<img width="1500" alt="sample product category 20160719" src="https://cloud.githubusercontent.com/assets/5397325/16943448/21fd02b0-4ddf-11e6-8a63-777331997297.png">

**Comment by demiscient** [comment]
Not bad, getting there, I think? Except for that footer, wtf is happening there..
