### ISSUE TITLE
Double check the wishlist functionality

### ISSUE THREAD

**Issue by brandonsheppard** [demiscient/demitheme#16]
Looks like you have changed the wishlist text to be a ❤️ in the template, but not [in the Javascript](https://github.com/demiscient/demitheme/blob/master/src/js/custom.js#L11-L12).

**Comment by demiscient** [comment]
I don't understand; it appears to not be referenced as a star in the Javascript code anywhere

**Comment by demiscient** [comment]
checked the wishlist functionality while logged in, works normally as expected
