### ISSUE TITLE
🎉

### ISSUE THREAD

**Issue by brandonsheppard** [demiscient/demitheme#19]
This is what your theme will look like when a customer installs it:

<img width="1100" alt="premiumthemes 20160831" src="https://cloud.githubusercontent.com/assets/5397325/18119538/89183e0c-6f9e-11e6-876c-ae5b88b250c9.png">

Can you please change the default banner to look nicer and have a link to documentation/instructions?

Kinda like what Rob's does:

<img width="1100" alt="premiumthemes 20160831 -1" src="https://cloud.githubusercontent.com/assets/5397325/18119630/e1527006-6f9e-11e6-9d3e-975670fb650f.png">

Great work! 😄

**Comment by demiscient** [comment]
n.b. http://premiumthemes.neto.com.au/?nview=august
