### ISSUE TITLE
Phil's Phound Phickels 

### ISSUE THREAD

**Issue by philcon93** [demiscient/demitheme#2]
## Home Page

- The USP shouldn't have a hover state if they don't like anywhere, but because these are adverts you can give them links, the html will just need to be changed

![screen shot 2016-07-19 at 5 55 49 pm](https://cloud.githubusercontent.com/assets/13529653/16942590/3b424cbc-4dda-11e6-8019-03131d035b5a.png)

- This 'view all' button doesn't go to a all brands page, it goes to a category

![screen shot 2016-07-19 at 6 01 34 pm](https://cloud.githubusercontent.com/assets/13529653/16942716/ed62de48-4dda-11e6-8f64-78a97a690252.png)
 

## Category Page

- The category full width banner - do not have a hover effect - indicates it does something/ links to somewhere. I would suggest to have the hover effect by default

![screen shot 2016-07-19 at 5 45 01 pm](https://cloud.githubusercontent.com/assets/13529653/16942306/b350548a-4dd8-11e6-80ab-161c5270e73c.png)

## Product Page

http://demirekt.neto.com.au/riveting

- There is an unclosed `[%/if%]` in the heading section

![screen shot 2016-07-19 at 5 31 50 pm](https://cloud.githubusercontent.com/assets/13529653/16941990/d4771eac-4dd6-11e6-8d46-0456ae6073cb.png)

- When a user selects a product variation and the product has alt images, the slick doesn't reload causing the image section to break and displays all of them not in a carousel:

![screen shot 2016-07-19 at 5 32 21 pm](https://cloud.githubusercontent.com/assets/13529653/16942007/f3a59c68-4dd6-11e6-89d1-a8caa0e34fb6.png)

- More a suggestion - the Calculator Shipping could go full width of its container

![screen shot 2016-07-19 at 5 35 08 pm](https://cloud.githubusercontent.com/assets/13529653/16942060/4c4c4b00-4dd7-11e6-9d0c-27faa85de89d.png)

- xs screen size - The product alt images are touching the main image, needs padding

![screen shot 2016-07-19 at 5 41 05 pm](https://cloud.githubusercontent.com/assets/13529653/16942205/343b233c-4dd8-11e6-9db7-4d484a57558b.png)

- Your product thumbnails indicate a product is on sale, but when you get to the product page it doesn't show anywhere if the product is on sale. Users need to confirm on the product page if this price is on sale or a normal price.

## Product Thumbnails

- Product thumbnails will have a title limit of 70 and products will not always have short title so we have to accommodate for this. The thumbnail on the right of the following image only has 27 characters

![screen shot 2016-07-19 at 5 38 43 pm](https://cloud.githubusercontent.com/assets/13529653/16942141/d4146b30-4dd7-11e6-8ff5-861d3d41ff74.png)

- on hover - the border is touching the title and price - needs padding

![screen shot 2016-07-19 at 5 43 22 pm](https://cloud.githubusercontent.com/assets/13529653/16942242/61160c3c-4dd8-11e6-8aca-20ec6baa99fd.png)

## Header

- xs screen size - There needs to be a user generated menu, or even a category menu in the header. Some users might not have a products page or will get rid of it so it would render your mobile header unuseable.

![screen shot 2016-07-19 at 5 58 31 pm](https://cloud.githubusercontent.com/assets/13529653/16942659/9f0a7a44-4dda-11e6-8099-51e7c41c0434.png)

- Cart icon - this icon will only support up to two digit number, not three digit numbers.

![screen shot 2016-07-19 at 6 07 20 pm](https://cloud.githubusercontent.com/assets/13529653/16942854/c2042bb6-4ddb-11e6-9405-6dd76c2008ca.png)

## Footer

- Subscription input - Need to decrease font size, my email is short and it is larger then this input box.

![screen shot 2016-07-19 at 5 49 20 pm](https://cloud.githubusercontent.com/assets/13529653/16942417/3dcf66e6-4dd9-11e6-930b-a10bce5d1e09.png)

## Account Summary Page

- class `.text-muted` is too light for a white background, as shown on this page

![screen shot 2016-07-19 at 5 52 30 pm](https://cloud.githubusercontent.com/assets/13529653/16942491/aa3a4d96-4dd9-11e6-882b-c822d5fb4d81.png)

## Cart popup

- The buttons letter spacing is too large

![screen shot 2016-07-19 at 6 04 27 pm](https://cloud.githubusercontent.com/assets/13529653/16942777/4f1da046-4ddb-11e6-9829-d1c56300e26b.png)

**Comment by demiscient** [comment]
Well, these instructions aren't working or I'm not applying them properly for the brands page to work :( https://www.neto.com.au/designer-documentation/tweak-library/content-page/brands-page/

**Comment by demiscient** [comment]
- Fixed product thumbnail names - smaller font now
- Removed surplus if statement closing tag - leftover from testing
- Title and price has border and padding on all viewports except XS because you can't hover on a mobile device anyways and the text could use the room
- Cart items now in a larger circle to benefit all of the 0.0017% of customers who will be buying hundreds of items from a store
- Footer subscribe area has smaller text now. Surprisingly hard to style the width of that sucker.
