### ISSUE TITLE
Mobile Menu

### ISSUE THREAD

**Issue by craigblunden** [demiscient/demitheme#28]
Should support up to 3 levels of navigation, had a custom complain.

https://www.adultdirect.com.au

**Comment by demiscient** [comment]
It does. See latest commit four months ago.

**Comment by craigblunden** [comment]
It only supports 2 when your desktop supports 3.

![screen shot 2017-06-28 at 4 37 41 pm](https://user-images.githubusercontent.com/11847839/27623508-23639664-5c20-11e7-8c4a-ff38b2d1fcbf.png)
