### ISSUE TITLE
Never target/style the grid system.

### ISSUE THREAD

**Issue by brandonsheppard** [demiscient/demitheme#3]
You should never add custom styles to components of the grid system. These include rows and columns (`col-`).

[Example](https://github.com/demiscient/demitheme/blob/master/src/css/app.less#L681-L683).

Instead, you should put a `div` inside the column and style that. If your layout requires it, rethink the layout.

This includes [inline styles](https://github.com/demiscient/demitheme/blob/master/src/templates/cms/home.template.html#L88) in the template.

**Comment by demiscient** [comment]
Hmmmm.. Skeletal seems to do it in a few places as well without much issue..
