### ISSUE TITLE
Sale label still shows when a sale has expired

### ISSUE THREAD

**Issue by matt-downs** [demiscient/demitheme#33]
`[@promo_price@]` should be `[@inpromo@]` otherwise the promo label will show even when a sale has expired:
https://github.com/demiscient/demitheme/blob/59b5a749fd866dfec8faaead3cb0fcd1796abeb8/src/templates/thumbs/product/template.html#L4
https://github.com/demiscient/demitheme/blob/59b5a749fd866dfec8faaead3cb0fcd1796abeb8/src/templates/thumbs/product/history.template.html#L4

**Comment by MilkyEngineer** [comment]
Fixed in f7ca372
