### ISSUE TITLE
Promo Tag showing on non-promo thumbnails

### ISSUE THREAD

**Issue by lanechr** [demiscient/demitheme#34]
The promo tag on thumbnails is currently populated based on [@promo_price@] meaning if a product has been in promo in the past but the time has elapsed on the promo, the tag will still appear for as long as the promo price field is populated.
This should be updated to populate based on [@inpromo@] being true.

**Comment by demiscient** [comment]
This issue was fixed AFAIK? #33

**Comment by lanechr** [comment]
Ah apologies. I was looking at the wrong version.
